cop_dataspace_opensearch:
  priority: 1
  description: 'Copernicus Dataspace with OpenSearch API'
  
  # Search plugin configuration (OpenSearch)
  search:
    plugin: 'QueryStringSearch'  # Built-in OpenSearch plugin
    api_endpoint: 'https://catalogue.dataspace.copernicus.eu/resto/api/collections/{collection}/search.json'
    need_auth: false
    timeout: 120
    ssl_verify: true
    pagination:
      next_page_query_obj: '{{\"page\": {page}, \"maxRecords\": {items_per_page}}}'
      total_items_nb_key_path: '$.properties.totalResults'
      max_items_per_page: 1000
    discover_metadata:
      auto_discovery: true
      metadata_pattern: 'https://catalogue.dataspace.copernicus.eu/resto/api/collections/{collection}/describe.xml'
      search_param: 'q'
    literal_search_params:
      format: 'json'
    constraints_file_url: 'https://catalogue.dataspace.copernicus.eu/resto/api/collections/describe.xml'
    results_entry: 'features'
    metadata_mapping:
      # Basic metadata mapping for OpenSearch
      uid: '$.id'
      title: '$.properties.title'
      geometry: '$.geometry'
      startTimeFromAscendingNode: '$.properties.startDate'
      completionTimeFromAscendingNode: '$.properties.completionDate'
      publicationDate: '$.properties.published'
      modificationDate: '$.properties.updated'
      platform: '$.properties.platform'
      instrument: '$.properties.instrument'
      productType: '$.properties.productType'
      processingLevel: '$.properties.processingLevel'
      orbitNumber: '$.properties.orbitNumber'
      relativeOrbitNumber: '$.properties.relativeOrbitNumber'
      orbitDirection: '$.properties.orbitDirection'
      cloudCover: '$.properties.cloudCover'
      sensorMode: '$.properties.sensorMode'
      polarizationChannels: '$.properties.polarisation'
      resolution: '$.properties.resolution'
      tileIdentifier: '$.properties.tileId'
      downloadLink: '$.properties.services.download.url'
      quicklook: '$.properties.quicklook'
      thumbnail: '$.properties.thumbnail'
  
  # Download plugin configuration
  download:
    plugin: 'HTTPDownload'  # Built-in HTTP download plugin
    extract: true
    archive_depth: 2
    ssl_verify: true
    timeout: 300
    chunk_size: 8192
  
  # Authentication plugin configuration (matching OData config)
  auth:
    plugin: 'KeycloakOIDCPasswordAuth'  # Keycloak OIDC plugin
    matching_url: 'https://catalogue.dataspace.copernicus.eu'
    oidc_config_url: 'https://identity.dataspace.copernicus.eu/auth/realms/CDSE/.well-known/openid-configuration'
    client_id: 'cdse-public'
    client_secret: null
    token_provision: 'qs'
    token_qs_key: 'token'
    auth_error_code: 401
    ssl_verify: true
    allowed_audiences: ["CLOUDFERRO_PUBLIC"]
    credentials:
      username: '${COPERNICUS_USERNAME}'
      password: '${COPERNICUS_PASSWORD}'
  
  # Complete product type mapping for all available collections
  products:
    # Sentinel-1 products
    S1_SAR_RAW:
      collection: 'SENTINEL-1'
      productType: 'RAW'
    S1_SAR_GRD:
      collection: 'SENTINEL-1'
      productType: 'GRD'
    S1_SAR_GRD_COG:
      collection: 'SENTINEL-1'
      productType: 'GRD-COG'
    S1_SAR_SLC:
      collection: 'SENTINEL-1'
      productType: 'SLC'
    S1_SAR_OCN:
      collection: 'SENTINEL-1'
      productType: 'OCN'
    
    # Sentinel-2 products  
    S2_MSI_L1C:
      collection: 'SENTINEL-2'
      productType: 'S2MSI1C'
    S2_MSI_L2A:
      collection: 'SENTINEL-2'
      productType: 'S2MSI2A'
